# Generated by Django 5.2.8 on 2025-12-01 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, help_text='ID del usuario que realiza la compra', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto total de la transacción', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text="Moneda de la transacción (ej. 'USD', 'EUR')", max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado'), ('CANCELLED', 'Cancelado')], default='PENDING', help_text='Estado actual de la transacción', max_length=10)),
                ('gateway_id', models.CharField(blank=True, help_text='ID de referencia de la pasarela de pago', max_length=255, null=True)),
                ('gateway_response', models.JSONField(blank=True, help_text='Respuesta completa de la pasarela de pago', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la transacción')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización de la transacción')),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, help_text='ID del usuario al que pertenece el método de pago', max_length=255)),
                ('gateway_token', models.CharField(help_text='Token seguro proporcionado por la pasarela de pago', max_length=255, unique=True)),
                ('card_brand', models.CharField(blank=True, help_text="Marca de la tarjeta (ej. 'Visa', 'Mastercard')", max_length=50, null=True)),
                ('last_four_digits', models.CharField(blank=True, help_text='Últimos cuatro dígitos de la tarjeta', max_length=4, null=True)),
                ('expiration_date', models.CharField(blank=True, help_text='Fecha de expiración (MM/AAAA)', max_length=7, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Indica si este es el método de pago por defecto del usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se guardó el método de pago')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del método de pago')),
            ],
            options={
                'verbose_name': 'Método de Pago Guardado',
                'verbose_name_plural': 'Métodos de Pago Guardados',
                'ordering': ['-created_at'],
                'unique_together': {('user_id', 'gateway_token')},
            },
        ),
    ]
