# Generated by Django 5.2.8 on 2025-12-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, help_text='ID de la orden o carrito asociado', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Moneda del pago (ej. USD, EUR)', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SUCCESS', 'Éxito'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='PENDING', help_text='Estado actual del intento de pago', max_length=10)),
                ('external_id', models.CharField(blank=True, help_text='ID de transacción en la pasarela de pago', max_length=255, null=True)),
                ('secure_environment_url', models.URLField(blank=True, help_text='URL del entorno seguro de la pasarela de pago', max_length=2000, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si el pago falla', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del intento de pago')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha y hora de actualización del intento de pago')),
            ],
            options={
                'verbose_name': 'Intento de Pago',
                'verbose_name_plural': 'Intentos de Pago',
                'ordering': ['-created_at'],
            },
        ),
    ]
