# Generated by Django 5.2.8 on 2025-11-27 02:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Entrega')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Puntuación (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_rating', to='feedback.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Calificación de Entrega',
                'verbose_name_plural': 'Calificaciones de Entrega',
                'constraints': [models.UniqueConstraint(fields=('order',), name='unique_delivery_rating_per_order')],
            },
        ),
    ]
