# Generated by Django 5.2.8 on 2025-12-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(help_text='Número único de seguimiento del ticket.', max_length=20, unique=True, verbose_name='Número de Ticket')),
                ('description', models.TextField(verbose_name='Descripción de la Incidencia')),
                ('status', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROGRESO', 'En Progreso'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=15, verbose_name='Estado')),
                ('reporter_email', models.EmailField(blank=True, help_text='Correo electrónico del cliente que reporta la incidencia.', max_length=254, null=True, verbose_name='Email del Reportador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
