# Generated by Django 5.2.8 on 2025-12-01 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('status', models.CharField(default='open', help_text="Estado actual de la sesión de chat (ej. 'open', 'closed').", max_length=50, verbose_name='Estado de la Sesión')),
            ],
            options={
                'verbose_name': 'Sesión de Chat',
                'verbose_name_plural': 'Sesiones de Chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(help_text="Quién envió el mensaje (ej. 'client', 'agent', 'bot').", max_length=50, verbose_name='Remitente')),
                ('content', models.TextField(verbose_name='Contenido del Mensaje')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Marca de Tiempo')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support_chat.chatsession', verbose_name='Sesión de Chat')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['timestamp'],
            },
        ),
    ]
