# Generated by Django 5.2.8 on 2025-12-01 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=100, unique=True, verbose_name='ID Repartidor')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud Actual')),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud Actual')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Última Actualización Ubicación')),
            ],
            options={
                'verbose_name': 'Repartidor',
                'verbose_name_plural': 'Repartidores',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='ID Pedido')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_TRANSIT', 'En Tránsito'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado del Pedido')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Dirección de Entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='tracking.deliveryperson', verbose_name='Repartidor Asignado')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='tracking.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Ubicación de Pedido',
                'verbose_name_plural': 'Ubicaciones de Pedido',
            },
        ),
    ]
