# Generated by Django 5.2.8 on 2025-12-01 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Token de pago')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca de tarjeta')),
                ('last_four_digits', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos')),
                ('expiry_month', models.IntegerField(verbose_name='Mes de expiración')),
                ('expiry_year', models.IntegerField(verbose_name='Año de expiración')),
                ('consent_given', models.BooleanField(default=False, verbose_name='Consentimiento otorgado')),
                ('is_default', models.BooleanField(default=False, verbose_name='Es predeterminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'unique_together': {('user', 'token')},
            },
        ),
    ]
